import { FORM230_ORG } from "@/lib/form230-config";
import type { Form230Record } from "@/lib/firestore-form230";

function attr(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&apos;");
}

/** Keep original casing (formular230.ro); only collapse whitespace. */
function xmlText(value: string, max: number): string {
  return value.replace(/\s+/g, " ").trim().slice(0, max);
}

function formatBorderouDate(d: Date): string {
  const dd = String(d.getDate()).padStart(2, "0");
  const mm = String(d.getMonth() + 1).padStart(2, "0");
  return `${dd}.${mm}.${d.getFullYear()}`;
}

export type B230BuildInput = {
  taxYear: number;
  nrBorderou: string;
  dataBorderou?: Date;
  rows: Form230Record[];
};

/**
 * B230 XML matching the format generated by formular230.ro
 * (xmlns mfp:anaf:dgti:b230:declaratie:v1, B230.xsd).
 */
export function buildB230Xml(input: B230BuildInput): string {
  const cui = FORM230_ORG.cui;
  const den = xmlText(FORM230_ORG.nameXml, 75);
  const iban = FORM230_ORG.ibanRon.replace(/\s/g, "").toUpperCase();
  const data = formatBorderouDate(input.dataBorderou ?? new Date());
  const nr = input.nrBorderou.replace(/\D/g, "") || "1";
  const count = input.rows.length;

  const declarations = input.rows.map((row, i) => {
    const nrPoz = String(i + 1);
    const nume = xmlText(row.nume, 75);
    const prenume = xmlText(row.prenume, 75);
    const valabilitate = row.durationYears === "1" ? "1" : "2";
    return (
      `<declaratie230 cif_c="${attr(row.cnp)}" nr_poz="${attr(nrPoz)}" nume_c="${attr(nume)}" prenume_c="${attr(prenume)}">` +
      `<bursa_entit bifa_entitate="1" den_entitate="${attr(den)}" cif_entitate="${attr(cui)}" cont_entitate="${attr(iban)}" acord="1" valabilitate_distribuire="${valabilitate}"/>` +
      `</declaratie230>`
    );
  });

  return (
    `<?xml version="1.0" encoding="UTF-8"?>\n` +
    `<borderou230 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="mfp:anaf:dgti:b230:declaratie:v1" xsi:schemaLocation="mfp:anaf:dgti:b230:declaratie:v1 B230.xsd" nr_borderou="${attr(nr)}" data_borderou="${attr(data)}" luna="12" an="${input.taxYear}" den="${attr(den)}" den_i="${attr(den)}" adresa_i="${attr(den)}" cui="${attr(cui)}" cif_i="${attr(cui)}" totalPlata_A="${count}">\n` +
    `\n` +
    `${declarations.join("")}` +
    `</borderou230>\n`
  );
}

export function b230Filename(dataBorderou = new Date()): string {
  const dd = String(dataBorderou.getDate()).padStart(2, "0");
  const mm = String(dataBorderou.getMonth() + 1).padStart(2, "0");
  return `Borderou__${dd}-${mm}-${dataBorderou.getFullYear()}.xml`;
}
